# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  workflow_dispatch:
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: rwood-97
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: living-with-machines
          repo: mapreader
          template: repository
          filename: metrics.mapreader.svg
          config_timezone: Europe/London
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_stargazers_days: 0
          plugin_stargazers_charts_type: graph
          
