name: Test missing-license

on:
  workflow_dispatch:

jobs:
  missing-license:
    runs-on: ubuntu-latest
    steps:
      - uses: alan-turing-institute/missing-license@main
        with:
          gh_token: ${{ secrets.PAT }}
          organization: rwood-97
          dry_run: "true"
